name: Mac Artifacts

on:
  push:
    branches: ci

# on:
#   workflow_dispatch:
#     inputs:
#       release_tag:
#         description: "Release version tag"
#         required: true

env:
  CFG_WORKING_DIR: "config"

jobs:      
  generate_mac_artifacts:
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Copy the license file into all directories
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          cp LICENSE build/mac/AQ_Install/AQ.app/Contents/Resources/

      - name: Zip game contents to pkz
        working-directory: ${{ env.CFG_WORKING_DIR }}/action
        run: |
          for makepkz in default-configs default-game-content default-mappack0 default-mappack1 default-pics default-sounds; do
            cd ${makepkz}
            zip -r ../0_${makepkz}.pkz * && cd ..
            rm -rf ${makepkz}/
          done

      # Standalone
      - name: Generate Mac Standalone artifacts
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash package_mac.sh standalone

      - name: Generate Universal Standalone DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-dmg-standalone
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal-standalone.dmg

      - name: Generate Universal Standalone zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-zip-standalone
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal-standalone.zip

      # Steam
      - name: Generate Mac Steam artifacts
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash package_mac.sh steam

      - name: Generate Universal Steam DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-dmg-steam
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal-steam.dmg

      - name: Generate Universal Steam zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-zip-steam
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal-steam.zip
