name: New Content Release

on:
  # push:
  #   branches: ci
  workflow_dispatch:

env:
  DIST_DIR: "config"

jobs:      
  generate_content_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v4
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Fetch additional history
        working-directory: ${{ env.DIST_DIR }}
        run: |
          # Set up partial clone support
          git config remote.origin.promisor true
          git config remote.origin.partialclonefilter blob:none
          # Now fetches history (but not blobs!)
          git fetch --unshallow

      - name: Zip game content to pkz
        working-directory: ${{ env.DIST_DIR }}/baseaq
        run: |
          for makepkz in pak0 pak1; do
            cd ${makepkz}
            python $GITHUB_WORKSPACE/${{ env.DIST_DIR }}/scripts/pkz/pkz.py ../${makepkz}.pkz * && cd ..
            rm -rf ${makepkz}/
          done

      - name: Copy premade pkz's into action
        working-directory: ${{ env.DIST_DIR }}
        run: |
          mv paks/zz_billboard_textures.pkz action/zz_billboard_textures.pkz

      - name: Copy remote pkz's into baseaq
        working-directory: ${{ env.DIST_DIR }}
        run: |
          cd baseaq/ && wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://gameassets.aq2world.com/action/2023_25thAnniversary_mapjam.pkz

      - name: Copy remote files into action
        working-directory: ${{ env.DIST_DIR}}
        run: |
          wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" http://gameassets.aqtiongame.com/action/bots/navmesh.zip

      - name: Extract bots + navmesh files
        working-directory: ${{ env.DIST_DIR}}
        run: |
          unzip -oq navmesh.zip -d action/
          rm -rf navmesh.zip

      - name: Download all library files for Windows, Linux and Linux ARM
        run: |
          for FILE in q2pro-darwin-arm64 q2pro-lin-arm64 q2pro-lin-gcc-x86_64 q2pro-msvc-x64; \
          do wget -qnv https://github.com/actionquake/aq2-tng/releases/latest/download/${FILE}.zip \
          && unzip -o ${FILE}.zip -d ${{ env.DIST_DIR }}/baseaq/ \
          && unzip -o ${FILE}.zip -d ${{ env.DIST_DIR }}/action/ \
          && rm -rf ${{ env.DIST_DIR }}/baseaq/q2pro* \
          && rm -rf ${{ env.DIST_DIR }}/action/q2pro* \
          ; done

      - name: Make all libraries executable
        run: |
          chmod +x ${{ env.DIST_DIR }}/baseaq/game*
          chmod +x ${{ env.DIST_DIR }}/action/game*

      - name: Generate dist files
        run: |
          cd ${{ env.DIST_DIR }} && zip -r aqtion-content.zip versions baseaq/ action/

      - name: Generate archive
        uses: actions/upload-artifact@v4
        with:
          name: aq-content-only
          path: |
            ${{ env.DIST_DIR }}/aqtion-content.zip

      - name: 'Post-build cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

